### ISSUE TITLE
Piping & HT discovery

### ISSUE THREAD

**Issue by Gustav-Eikaas** [equinor/cc-components#332]
Figure out what needs to be done to split piping & ht app in two. Consult with Atle for details

1. Piping workspace (with pipetest as main object)
2. HT workspace (with heat tracing cable as main object)

**Comment by ken-mellem** [comment]
https://miro.com/app/board/uXjVMZPHKgo=/

The decision is to split the existing JCA Piping and Heat trace into two separate application. We will need to include Atle in refinement.

- Discovery 
- When the time is right - come up with a high-level estimate (days) - add it to Estimates on the Issue in the Project.

**Comment by MagnusGjosund** [comment]
Can't do anymore before i get SQL-view

**Comment by aman-riaz** [comment]
Meeting with 07.06 with Atle, Magnus and Are. 
Key highlights: 
- Data coming from MIPS to JC wil come through Pcs for OGP (and other projects). This is a new column that has been added to pcs this week, and is planned to soon be available in FAM 
- Split Piptest and HT so that we avoid duplicates, due to many to many relationship between PT and HT. This will result in two views. 
- Agree that I will look more into this, and will revert back with questions and follow up

**Comment by ken-mellem** [comment]
Replaced by 
- equinor/lighthouse#303
- equinor/lighthouse#312
