### ISSUE TITLE
🎁: [Heat Trace] Data foundation - follow up issue 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#747]
This is a follow up issue where Aman and Magnus will update the latest status on HT data.

Magnus status 07.12.23: Still waiting on the data. Got a new HTChecklist view a day ago, but the data fundation is deficient. I need @aman-riaz to give a better and supplementary status.

**Comment by aman-riaz** [comment]
The following checklists are now added:
- checklists directly related to HT 
- checklists indirectly related via Pipetest 
- checklits indirectly related via circuit 

New adjustments are added now to the view, and will validate tomorrow with Magnus how the data looks like in the app. Currently only the direct checklists and indirect via circuit are available, because we still have no sufficient data in FAM that connects HT and Pipetest. This is data that the contractors need to send to PCS which can be imported into FAM. 

Few rows have entered into FAM, but there has been an issue with mapping between pcs, fam and commonlib due to which the piptest column is null. FAM is on this, and will revert back when they know more.

**Comment by MagnusGjosund** [comment]
Updated the views from Custom_HeatTrace --> Custom_HeatTraceV2 and Custom_HeatTraceChecklistV2 --> Custom_HeatTraceChecklistV3. Done in frontend and backend.

**Comment by aman-riaz** [comment]
Data ready for validation. The views are optimized for better performance. Meeting with Atle, Jone, Magnus this week to go through the data in app/report to ensure it shows the right numbers. 

Updates HeatTraceCablePipeTest: Pipetest column now corrected. We have raised the issue to populate this table with more data in the FAM/JC/PCS chat. Following up on this.

**Comment by aman-riaz** [comment]
Meeting 19.01.24
Validated data against ProCoSys with Jone, Magnus, Ken. Data seems to be correct now. 

Changes requested in FAM view:
- If all steps are completed --> checkliststep will be "Completed"
- CPCL should not be included 
- Remove C for complete 

I will implement the changes and update when they are in prod. No changes are required in the app.

**Comment by aman-riaz** [comment]
The above-mentioned changes are complete. 

@MagnusGjosund  can we close this?
