### ISSUE TITLE
🐛: Missing KPI value

### ISSUE THREAD

**Issue by JoneUE** [equinor/cc-components#801]
## Description

Missing value in KPI

![Image](https://github.com/equinor/cc-components/assets/73601851/8b620143-aee3-461e-9817-786d38dc951d)

**Comment by JoneUE** [comment]
![Image](https://github.com/equinor/cc-components/assets/73601851/223dc035-a052-4da0-8fcb-bed6ea51c49f)

Burde ikke SignedDate bli lagt til i models?

**Comment by kjellhaaland** [comment]
The issue was related to mapping between the FAM models and the API models, and is fixed.

In the future we should add Unit-tests for the model mappings. 
I have created equinor/fusion-data-gateway#465 to follow up on creating tests.

The fix is deployed to test. @JoneUE, can you verify its ready for prod?
Link: https://webserver-fusion-project-portal-test.radix.equinor.com/apps/loop/94dd5f4d-17f1-4312-bf75-ad75f4d9572c?tab=grid

**Comment by JoneUE** [comment]
Looks good, can send to prod
