### ISSUE TITLE
🎁: Heat trace - Table - Need more columns 

### ISSUE THREAD

**Issue by MagnusGjosund** [equinor/cc-components#856]
## Expected outcome
Need more columns in table. Look at pipings miro board ( https://miro.com/app/board/uXjVNM_KarU=/ )

New columns:
- MC Handover Status
- Comm Priority 2
- Comm Priority 3
- Comm Identifier
- MC responsible
- MC Phase

@aman-riaz i think Custom_HeatTraceV2 is missing data for "MC Handover Status", "Comm Identifier" and "MC phase". Are you able to add these? 

## Business Value / Developer Experience
Better ux

## Acceptance Criteria
See that the correct columns is added

**Comment by aman-riaz** [comment]
Added following fields to Custom_HeatTrace_V2:

- MechanicalCompletionPhase
- MechanicalCompletionHandoverStatus 
- CommissioningIdentifierCode
- CommissioningIdentifierDescription (This is the full description of the Identifier Code) 

The execution time of the view has increased with around 15-20 seconds due to addition of more joins and data. Not sure if this will be noticable in the app or not. @MagnusGjosund Please let me know if you experience slower data fetch.

**Comment by MagnusGjosund** [comment]
Put on-hold. More important bugs/issues on RC right now

**Comment by MagnusGjosund** [comment]
PR Backend: https://github.com/equinor/fusion-data-gateway/pull/508
PR Frontend: https://github.com/equinor/cc-components/pull/864
